In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
df = pd.read_csv('boston.csv')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [ ]:
dataset=df.select_dtypes(include=np.number)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dataset.iloc[:, :-1], dataset.iloc[:, -1], test_size=0.2, random_state=0)

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

WARNING:tensorflow:From c:\Users\shrey\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss='mse')

In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

WARNING:tensorflow:From c:\Users\shrey\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

In [ ]:
y_pred = model.predict(X_test)
print("Predicted house prices:", y_pred)

4/4 [==============================] - 0s 5ms/step
Predicted house prices: [[22.21006  ]
 [27.61399  ]
 [25.552383 ]
 [ 9.22378  ]
 [17.385963 ]
 [19.344559 ]
 [22.013645 ]
 [20.914608 ]
 [18.336021 ]
 [21.245884 ]
 [ 8.153291 ]
 [ 9.715223 ]
 [14.081897 ]
 [ 6.232585 ]
 [46.08608  ]
 [33.457226 ]
 [23.587788 ]
 [36.873016 ]
 [31.876331 ]
 [22.823595 ]
 [23.547493 ]
 [18.9805   ]
 [20.401163 ]
 [26.491554 ]
 [21.947659 ]
 [27.707033 ]
 [16.56754  ]
 [16.196234 ]
 [40.225945 ]
 [18.047516 ]
 [13.549348 ]
 [15.64262  ]
 [21.152918 ]
 [17.345367 ]
 [25.384893 ]
 [21.023064 ]
 [ 6.529188 ]
 [38.621246 ]
 [10.966916 ]
 [13.94802  ]
 [24.429857 ]
 [22.864618 ]
 [18.063028 ]
 [16.38615  ]
 [21.575274 ]
 [22.91457  ]
 [21.34613  ]
 [13.859373 ]
 [14.583705 ]
 [23.242294 ]
 [ 7.689764 ]
 [22.816235 ]
 [21.515045 ]
 [43.716656 ]
 [11.021136 ]
 [20.699644 ]
 [15.357165 ]
 [18.048145 ]
 [21.91293  ]
 [22.136925 ]
 [19.724648 ]
 [19.416067 ]
 [32.711456 ]
 [33.018345 ]
 [18.041725 ]
 [29.220085 ]
 [15.139957 ]
 [21.91196  ]
 [ 9.766297 ]
 [23.068745 ]
 [17.69272  ]
 [20.23131  ]
 [26.488415 ]
 [27.06757  ]
 [27.058125 ]
 [ 5.8159056]
 [41.767563 ]
 [21.893774 ]
 [25.338997 ]
 [17.4857   ]
 [23.838993 ]
 [19.199778 ]
 [20.56514  ]
 [42.097355 ]
 [46.213886 ]
 [22.636711 ]
 [24.186964 ]
 [11.156676 ]
 [27.022177 ]
 [14.476474 ]
 [12.365865 ]
 [ 7.9925833]
 [19.742615 ]
 [26.96849  ]
 [20.963062 ]
 [19.893452 ]
 [ 8.539683 ]
 [21.462967 ]
 [12.610639 ]
 [17.751526 ]
 [24.064766 ]
 [20.580269 ]]